// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BottomBar: typeof import('./../components/bottomBar/index.vue')['default']
    HomeBanner: typeof import('./../components/homeBanner/index.vue')['default']
    Logo: typeof import('./../components/logo/index.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
